language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: USXCI08WE1MPaEx5xIgseR0CByPE5/6P+zDCKvbrn2RYzAqmUj7kuEgu7P6nttX0lDj6C/b7z1ywRuqG3ELcVg4pMKH2a4sLclX6RSC+pGIMjv4vRt2/9UNQU3O8nsY/kQLbrnVgex/ypecN1Gq6AfMDz+dM2w+3lp/A1hbF6gjT5VG9iX+fdDZE5Bpmhy9y4VQOKPDZd25ddnsnyBPnnF32K8YLMf0AGtHCOtE3rlECikf90ebMmbW9kjeSv2xNuc0mnamcKn+kVRMcg+16RUaOXwNOwjZTP8MNUHhLfL4YprPw//h0nzhDGeG/GbJ0HDnCHgqgyO5wJrZ/I9Hkxc9JQnhFagLklWIdv+5mOtfzF6WZHC22+mePqvw9VkSTuEfVQq5HBMka4z43R2EfRVuWvxuEbXTaaTe2ry+8Ne1DEmq/dJ4bawSEy1K87T1zkay0BRnYurOsUDA8jVCQT1wQsMu1jqxKYnB4vEeaP2y1zMCdpgEZzcd6lzk0E1fS84l6PhgQIm+M9C4pmSQorPdMmpx4ZP90fjUTghOxBqWkRMIESrv5+/6ILnUZoXwWfAZnIV67TI54QwdElWO/tJ42jyXVtt8u3TbbdlRC4+BnTF/j/SZom0xzGkZlQ6yu49G89/RoBj72IlOm6OP/4iDRYnSzAG4fQO9PlBD0E18=
  app: shrouded-headland-53344
  on:
    repo: rcaseyx/new-best-friend
